config/routes.rb
Rails.application.routes.draw do

  resources :credentials

  get 'sessions/new'

  resources :applications
  resources :environments
  resources :schemas
  resources :deployments
  resources :applications do
    resources :environments do
      resources :schemas
    end
  end

  resources :dashboards
  resources :database_change_logs
  resources :users

  root 'static_pages#home'
  get  'static_pages/home'
  get  'static_pages/help'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/application.rb
# == Schema Information
#
# Table name: applications
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Application < ActiveRecord::Base
	has_many :environments
	has_many :schemas

	validates :name, presence: true
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from ActiveRecord::NoDatabaseError, :with => :database_not_found
	def database_not_found
		set_internal_database
		respond_to do |format|
			flash[:error] = 'Could not connect to Schema.'
			format.html { redirect_to schemas_url }
		end
	end

	def set_Schema_Connection(schema)
		begin
		  ActiveRecord::Base.establish_connection(
		    :adapter  => "#{schema.database_type}",
		    :host     => "#{schema.host}",
		    :port     => "#{schema.port}",
		    :username => "#{schema.username}",
		    :password => "#{schema.password}",
		    :database => "#{schema.name}"
		    )
	  	return 0
    rescue
      set_internal_database
      return 1
    end
	end

	# Login

	# Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

	# Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

	# Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end

	# Logs in the given user.
  def log_in(user)
    session[:user_id] 	 = user.id
    session[:user_name]  = user.name
    session[:user_email] = user.email
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    session.delete(:user_name)
    session.delete(:user_email)
    @current_user = nil
  end

  protected
  
  include SessionsHelper
  
  SESSION_TIMEOUT = 15            # in minutes
  
  def authorize
    unless User.find_by_name(session[:user_name])
      redirect_to login_url
      # redirect_to login_url, :alert => t(:session_login) 
    end
  end
	
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authorize
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :set_internal_database

  def index
    @applications = Application.all
  end

  def show
  end

  def new
    @application = Application.new
  end

  def edit
  end

  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        flash[:success] = 'Application was successfully created.'
        format.html { redirect_to applications_path }
        #format.html { redirect_to @application, notice: 'Application was successfully created.' }
        #format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :description)
    end

    def set_internal_database
      ActiveRecord::Base.establish_connection(
        :adapter  => "sqlite3",
        :database => "db/lbview_#{Rails.env}.sqlite3"
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  include ApplicationsHelper
  include EnvironmentsHelper
  include SchemasHelper

  def set_internal_database()
    ActiveRecord::Base.establish_connection(
      :adapter  => "sqlite3",
      :database => "db/lbview_#{Rails.env}.sqlite3"
    )
  end

  def set_Schema_Connection(schema)
    begin
      ActiveRecord::Base.establish_connection(
        :adapter  => "#{schema.database_type}",
        :host     => "#{schema.host}",
        :port     => "#{schema.port}",
        :username => "#{schema.username}",
        :password => "#{schema.password}",
        :database => "#{schema.name}"
        )
      return 0
    rescue
      set_internal_database
      return 1
    end
  end

  def bootstrap_class_for flash_type
    case flash_type
      when "success"
        "alert-success" # Green
      when "error"
        "alert-danger" # Red
      when "alert"
        "alert-warning" # Yellow
      when "notice"
        "alert-info" # Blue
      else
        flash_type.to_s
    end
  end

end

app/helpers/applications_helper.rb
module ApplicationsHelper
  
  def get_Application_Count()
    applications = Application.all
    count = 0
    if applications
      count = applications.count
    end
    count
  end

  def get_Application_Name(id)
    application = Application.find_by_id(id)
    application.name
  end

  def get_Application_Schemas_List(id)
    set_internal_database()
    schemaList = ""
    schemas = Schema.where("application_id >= '#{id}'")
    schemas.each do |s|
      if !schemaList.include? s.name
        schemaList << s.name + ", "
      end
    end
    if schemaList == ""
      return "No schemas defined and/or associated."
    else
      return schemaList.chop.chop
    end
  end

  def user_can_status(schema_id)
    credentials = Credential.where("schema_id = '#{schema_id}' AND user_id = '#{session[:user_id]}'")
    if credentials == nil 
      return false
    end
    credentials.each do |credential|
      if credential.status == true
        return true
      else
        return false
      end
    end
  end

  def user_can_snapshot(schema_id)
    credentials = Credential.where("schema_id = '#{schema_id}' AND user_id = '#{session[:user_id]}'")
    if credentials == nil 
      return false
    end
    credentials.each do |credential|
      if credential.snapshot == true
        return true
      else
        return false
      end
    end
  end

  def user_can_forecast(schema_id)
    credentials = Credential.where("schema_id = '#{schema_id}' AND user_id = '#{session[:user_id]}'")
    if credentials == nil 
      return false
    end
    credentials.each do |credential|
      if credential.forecast == true
        return true
      else
        return false
      end
    end
  end

  def user_can_deploy(schema_id)
    credentials = Credential.where("schema_id = '#{schema_id}' AND user_id = '#{session[:user_id]}'")
    if credentials == nil 
      return false
    end
    credentials.each do |credential|
      if credential.deploy == true
        return true
      else
        return false
      end
    end
  end
  
end

app/views/applications/_form.html.erb
<%= form_for(@application, html: {class: "form-horizontal"}) do |f| %>

  <% if @application.errors.any? %>
  <div id="errorExplanation" class="bs-callout bs-callout-danger">
    <h4><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h4>
    <ul>
    <% @application.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="well">

  <div class="field form-group">
    <%= f.label :'Application Name', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'Description', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit @application.new_record? ? 'Create' : 'Update', :class => 'btn btn-primary btn-xs' %>
      <%= link_to 'Cancel', applications_path, :class => 'c_textlink' %>
    </div>
  </div>
  </form>

</div> 

<% end %>

app/views/applications/edit.html.erb
<div class="panel panel-red">
  <div class="panel-heading">
    <i class="fa fa-list-alt fa-2x"></i><b> <big><big>Edit Application: <b><%= @application.name %></b></big></big></b>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Applications', applications_path %></li>
  <li class="active"><%= link_to 'Add Application', new_application_path %></li>
</ul>

<%= render 'form' %>

app/views/applications/index.html.erb
<div class="panel panel-red">
  <div class="panel-heading">
    <i class="fa fa-list-alt fa-2x"></i><b> <big><big>Applications</big></big></b>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'Applications', applications_path %></li>
  <li><%= link_to 'Add Application', new_application_path %></li>
</ul>

<div class="table">

<table class="table table-striped table-bordered table-hover table-condensed ">
  <thead>
    <tr>
      <th class="col-md-3">Appliction Name</th>
      <th class="col-md-3">Description</th>
      <th class="col-md-4">Schemas</th>
      <th class="col-md-2" colspan="4" style="text-align:center;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{application.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{application.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= link_to application.name, application, :class => 'c_textlink' %>
          </span>
        </td>
        <td><%= application.description %></td>
        <td><%= get_Application_Schemas_List(application.id) %></td>
        <td style="text-align:center;"><%= link_to 'Show', application, class: 'btn btn-primary btn-xs c_btnlink' %></td>
        <td style="text-align:center;"><%= link_to 'Edit', edit_application_path(application), class: 'btn btn-primary btn-xs c_btnlink' %></td>
        <td style="text-align:center;"><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-xs c_btnlink' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/applications/new.html.erb
<div class="panel panel-red">
  <div class="panel-heading">
    <i class="fa fa-list-alt fa-2x"></i><b> <big><big>Add Application</big></big></b>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Applications', applications_path %></li>
  <li class="active"><%= link_to 'Add Application', new_application_path %></li>
</ul>

<%= render 'form' %>

app/views/applications/show.html.erb
<div class="panel panel-red">
  <div class="panel-heading">
    <i class="fa fa-list-alt fa-2x"></i><b> <big><big>Application: </b><%= @application.name %></big></big></b>    <small><%= @application.description %></small>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'Applications', applications_path %></li>
  <li><%= link_to 'Add Application', new_application_path %></li>
</ul>

<% if @application.environments.count != 0 %>

  <% @application.environments.each do |environment| %>

  <div class="row">
  <div class="col-lg-12">
      <div class="panel panel-yellow">
        <div class="panel-heading">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= environment.id %>" class="c_panelheadinglink">
            <big><i class="fa fa-sitemap fa-fw"></i>Environment:  <b><%= environment.name %></b></big><small> <%= environment.description %></small>
          </a>
        </div>

        <div id="collapse<%= environment.id %>" class="panel-body panel-collapse collapse in">
          <div class="list-group">

          <table class="table table-hover table-bordered table-condensed table-striped">
            <thead>
              <tr>
                <th>Schema</th>
                <th>Hostname</th>
                <th>Status</th>
                <th>ChangeLog Table</th>
                <th>Lastest Deployed Change</th>
                <th>Lastest Deployed Date</th>
                <th style="text-align:left;">Actions</th>
              </tr>
            </thead>
            <tbody>
            <% if environment.schemas.count != 0 %>
            <% environment.schemas.each do |schema| %>
            <tr class="">
                <td>
                  <%= link_to schema.name, database_change_logs_path(:id => schema.id, :schemaName => schema.name, :databaseChangeLogTable => schema.changelogtable), class: 'c_textlink' %>
                </td>
                <td><%= schema.host %></td>
                <td><big><%= raw get_Schema_Deployments_Status(schema) %></big></td>
                <td><%= schema.changelogtable %></td>
                <td><%= get_Schema_Deployment_Latest_ChangeSet(schema) %></td>
                <td><%= get_Schema_Deployment_Latest_ExecDate(schema).strftime("%Y-%m-%d %H:%M") %></td>
                <td style="text-align:left;">

                  <% if user_can_status(schema.id) %>
                    <%= link_to database_change_logs_path(:id => schema.id, :schemaName => schema.name, :databaseChangeLogTable => schema.changelogtable), class: "btn btn-gray btn-xs c_btnlink" do %>
                        <i class="fa fa-bars"> Status</i>
                    <% end %>
                  <% end %>

                  <% if user_can_snapshot(schema.id) %>
                    <%= link_to database_change_logs_path(:id => schema.id, :schemaName => schema.name, :databaseChangeLogTable => schema.changelogtable), class: "btn btn-gray btn-xs c_btnlink" do %>
                        <i class="fa fa-download"> Snapshot</i>
                    <% end %>
                  <% end %>

                  <% if user_can_forecast(schema.id) %>
                    <%= link_to schema, class: "btn btn-gray btn-xs c_btnlink" do %>
                        <i class="fa fa-check-square"> Forecast</i>
                    <% end %>
                  <% end %>

                  <% if user_can_deploy(schema.id) %>
                    <%= link_to schema, class: "btn btn-gray btn-xs c_btnlink" do %>
                        <i class="fa fa-arrow-circle-right"> Deploy</i>
                    <% end %>
                  <% end %>
                   
                    
                </td> 
              </tr>
            <% end %>
            <% else %>
            <tr class="">
              <td colspan="7"><span class="label label-warning"><big>No schemas defined and/or associated with environment.</big></span><br/></td>
            </tr>
          <% end %>
            </tbody>
          </table>

          </div>
        </div>
      </div>
  </div>
  </div>
<% end %>
<% else %>
  <tr class="">
    <td colspan="7"><span class="label label-warning">No environments associated with application.</span><br/></td>
  </tr>
<% end %>


<%= link_to 'Back', applications_path, class: 'c_textlink' %>