config/routes.rb
Rails.application.routes.draw do

  resources :credentials

  get 'sessions/new'

  resources :applications
  resources :environments
  resources :schemas
  resources :deployments
  resources :applications do
    resources :environments do
      resources :schemas
    end
  end

  resources :dashboards
  resources :database_change_logs
  resources :users

  root 'static_pages#home'
  get  'static_pages/home'
  get  'static_pages/help'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/views/layouts/_alert.html.erb
<div class="col-xs-12">
	<% flash.each do |name, msg| %>
    <div class="alert <%= bootstrap_class_for(name) %> alert-dismissable fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation_left.html.erb
<nav class="navbar navbar-left navbar-inverse side-nav" role="navigation-left">
  <ul class="nav navbar-nav side-nav">

    <li class="active">
      <%= link_to dashboards_path do %>
        <i class="fa fa-fw fa-dashboard"></i> Dashboard
      <% end %>
    </li>

    <li class="active">
      <%= link_to applications_path do %>
        <i class="fa fa-fw fa-list-alt"></i> Applications
      <% end %>
    </li>

    <li class="active">
      <%= link_to environments_path do %>
        <i class="fa fa-fw fa-sitemap"></i> Environments
      <% end %>
    </li>

    <li class="active">
      <%= link_to schemas_path do %>
        <i class="fa fa-fw fa-database"></i> Schemas
      <% end %>
    </li>

    <li class="active">
      <%= link_to deployments_path do %>
        <i class="fa fa-fw fa-tasks"></i> Deployments
      <% end %>
    </li>

    <% if logged_in? %>
      <% if session[:user_name] == 'admin' %>
        <li class="active">
          <%= link_to users_path do %>
            <i class="fa fa-fw fa-user"></i> Users
          <% end %>
        </li>
         <li class="active">
          <%= link_to credentials_path do %>
            <i class="fa fa-fw fa-key"></i> Credentials
          <% end %>
        </li>
      <% end %>
    <% end %>

  </ul>
</nav>

app/views/layouts/_navigation_top.html.erb
<!-- app/views/layouts/_navigation_top.html.erb -->

  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation-top">

    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></i></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
       <li class="active"><span class="navbar-brand" style="vertical-align: top;"><i class="fa fa-power-off fa-1x"></i> Datical DB[Dashboard]</span>><</li>
    </div>

    <!-- Top Bar Left Menu Items -->

    

    <!-- Top Bar Right Menu Items -->

    <ul class="nav navbar-nav navbar-right">

      <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-user"></i> <%= session[:user_name] %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
          </ul>
        </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-gear"></i> Settings <b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#">Configure</a></li>
        </ul>
      </li>

    <% else %>
      # Links for non-logged-in-users
    <% end %>

    </ul>

  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
  <title>DaticalDB[Dashboard]</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div id="main-container" class="wrapper">
    <%= render 'layouts/navigation_top' %>

    <div class="row">

      <div class="col-xs-2">
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <%= render 'layouts/navigation_left' %>
          </ul>
        </div>
      </div>

      <div class="col-xs-9">
        <div class="row">
          <%= render 'layouts/alert' %>
        </div>
        <div class="row">
          <%= yield %>
        </div> 
      </div>

    </div>
  </div>

</body>
</html>