config/routes.rb
Rails.application.routes.draw do

  resources :credentials

  get 'sessions/new'

  resources :applications
  resources :environments
  resources :schemas
  resources :deployments
  resources :applications do
    resources :environments do
      resources :schemas
    end
  end

  resources :dashboards
  resources :database_change_logs
  resources :users

  root 'static_pages#home'
  get  'static_pages/home'
  get  'static_pages/help'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/schema.rb
# == Schema Information
#
# Table name: schemas
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  database_type  :string(255)
#  host           :string(255)
#  port           :string(255)
#  username       :string(255)
#  password       :string(255)
#  changelogtable :string(255)
#  application_id :integer
#  environment_id :integer
#  created_at     :datetime
#  updated_at     :datetime


class Schema < ActiveRecord::Base

	DATABASE_TYPES = ["mysql2", "postgresql"]

	validates :name, presence: true
	validates_inclusion_of :database_type, :in => %w(mysql2 postgresql)
	validates :host, presence: true
	validates :port, numericality: { only_integer: true }
	validates :username, presence: true
	validates :password, presence: true
	validates :changelogfile, presence: true
	validates :changelogtable, presence: true
	validates :application_id, presence: true
	validates :environment_id, presence: true
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController
  before_filter :authorize
  before_action :set_schema, only: [:show, :edit, :update, :destroy]
  before_action :set_internal_database

  def index
    @schemas = Schema.all
  end

  def show
  end

  def new
    @schema = Schema.new
  end

  def edit
  end

  def create
    @schema = Schema.new(schema_params)

    respond_to do |format|

      if set_Schema_Connection(@schema) == 0
        if ActiveRecord::Base.connection.table_exists? @schema.changelogtable
          set_internal_database
          if @schema.save
            flash[:success] = 'Schema was successfully created.'
            format.html { redirect_to @schema }
            #format.html { redirect_to @schema, notice: 'Schema was successfully created.' }
            #format.json { render :show, status: :created, location: @schema }
          else
            format.html { render :new }
            format.json { render json: @schema.errors, status: :unprocessable_entity }
          end
        else
          set_internal_database
          flash[:error] = 'Connected to Schema but does not appear to be managed by Liquibase.'
          format.html { redirect_to schemas_url }
        end
      else
        set_internal_database
        flash[:error] = 'Could not connect to Schema.'
        format.html { redirect_to schemas_url }
      end
    end
  end

  def update
    respond_to do |format|
      if @schema.update(schema_params)
        flash[:success] = 'Schema was successfully updated.'
        format.html { redirect_to @schema }
        #format.html { redirect_to @schema, notice: 'Schema was successfully updated.' }
        #format.json { render :show, status: :ok, location: @schema }
      else
        format.html { render :edit }
        format.json { render json: @schema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schemas/1
  # DELETE /schemas/1.json
  def destroy
    @schema.destroy
    respond_to do |format|
      format.html { redirect_to schemas_url, notice: 'Schema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schema
      @schema = Schema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schema_params
      params.require(:schema).permit(:name, :database_type, :username, :password, :changelogfile, :changelogtable, :host, :port, :application_id, :environment_id)
    end

    def set_internal_database
      ActiveRecord::Base.establish_connection(
        :adapter  => "sqlite3",
        :database => "db/lbview_#{Rails.env}.sqlite3"
      )
    end
end

app/helpers/schemas_helper.rb
module SchemasHelper

	def get_Schema_Count()
    schemas = Schema.all
    count = 0
    if schemas
      count = schemas.count
    end
    count
  end

  def get_Schema_Deployments_Count(days)
  	totalChangeSets = 0
  	schemas = Schema.all

    now  = Date.today
    date =  (now - days).strftime("%Y-%m-%d %H:%M:%S")

    schemas.each do |schema|
      set_Schema_Connection(schema)
    	DatabaseChangeLog.table_name = schema.changelogtable
    	changeSets = DatabaseChangeLog.where("DATEEXECUTED >= '#{date}'")
	    if changeSets
	      totalChangeSets = totalChangeSets + changeSets.count
	    end
	   end
     set_internal_database()
	   totalChangeSets
  end

  def get_Schema_Deployment_Latest_ChangeSet(schema)
    set_Schema_Connection(schema)
    changeSet = DatabaseChangeLog.order("ORDEREXECUTED").last
    set_internal_database()
    changeSet.ID
  end

  def get_Schema_Deployments_Since_Date(days)
    now = Date.today
    date =  (now - days).strftime("%Y-%m-%d %H:%M:%S")
  end

  def get_Schema_Deployments_ChangeSets(week)
  	@listChangeSets = Array.new
  	schemas = Schema.all
    
    dateStart = (week).week.ago
    dateEnd 	= (week+1).week.ago
    puts dateStart
    puts dateEnd
    dateStart = dateStart.strftime("%Y-%m-%d %H:%M:%S")
    dateEnd   = dateEnd.strftime("%Y-%m-%d %H:%M:%S")

    rowColor = true
    schemas.each do |schema|
      set_Schema_Connection(schema)
      rowColor ^= true

    	DatabaseChangeLog.table_name = schema.changelogtable
    	changeSets = DatabaseChangeLog.where("DATEEXECUTED <= '#{dateStart}' AND DATEEXECUTED >= '#{dateEnd}'")
	    changeSets.each do |changeSet|
	      @listChangeSets.push schema.id
        @listChangeSets.push schema.name
        @listChangeSets.push schema.environment_id
        @listChangeSets.push schema.changelogtable
	      @listChangeSets.push changeSet.ID
	      @listChangeSets.push changeSet.DATEEXECUTED
	      @listChangeSets.push changeSet.DESCRIPTION
        @listChangeSets.push changeSet.COMMENTS
        @listChangeSets.push rowColor
	    end
	   end
     set_internal_database()
	   @listChangeSets
  end

  def get_Schema_Deployment_Latest_ExecDate(schema)
    set_Schema_Connection(schema)
    changeSet = DatabaseChangeLog.order("ORDEREXECUTED").last
    set_internal_database()
    changeSet.DATEEXECUTED
  end

  def get_Schema_Deployments_Status(schema)
    count = get_Schema_Deployments_Pending(schema).count
    if count > 0
      return "<span class='label label-warning'>Partially Deployed[#{count}]</span>"
    else
      return "<span class='label label-success'>Fully Deployed</span>"
    end
  end

  def get_Schema_Deployments_Pending(schemaID)
    set_internal_database
    schema = Schema.find(schemaID)
    changelog = XmlSimple.xml_in(schema.changelogfile)

    # Get ChangeSet id's
    change_sets = Array.new
    changelog['changeSet'].each do |item|
     item.sort.each do |k, v|
        if ["id"].include? k
           change_sets.push(v) if k=="id"
        end
      end
    end

    # Get the databasechangelog
    if set_Schema_Connection(schema) == 0
      database_change_log = DatabaseChangeLog.all

      # See if id's are in databasechangelog
      @undeployed_change_sets = Array.new
      if database_change_log.count != NIL
        change_sets.each do |cl_id|
          found = false
          database_change_log.each do |dbcl|
            if cl_id == dbcl.id
              found = true
            end
          end
          if !found
            @undeployed_change_sets.push(cl_id)
          end
        end
      end
    end

    set_internal_database()
    @undeployed_change_sets
  end

  def get_All_Schema_Deployments_Pending()
    schemas = Schema.all
    @all_undeployed_change_sets = Array.new
    schemas.each do |schema|
      get_Schema_Deployments_Pending(schema.id)
      if @undeployed_change_sets.count > 0
        @all_undeployed_change_sets.push schema.name
        @all_undeployed_change_sets.push @undeployed_change_sets
      end
    end
    @all_undeployed_change_sets
  end

end

app/views/schemas/_form.html.erb
<%= form_for(@schema, html: {class: "form-horizontal"}) do |f| %>

  <% if @schema.errors.any? %>
  <div id="errorExplanation" class="bs-callout bs-callout-danger">
    <h4><%= pluralize(@schema.errors.count, "error") %> prohibited this schema from being saved:</h4>
    <ul>
    <% @schema.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="well">

  <div class="field form-group">
    <%= f.label :'Schema Name', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'Database Type', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.select :database_type, Schema::DATABASE_TYPES.map { |s| s } %>
    </div>
  </div>  


  <div class="field form-group">
    <%= f.label :'Hostname', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :host, class: 'form-control' %>
    </div>
  </div>


  <div class="field form-group">
    <%= f.label :'Port', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :port, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'User Name', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'Password', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :password, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'ChangeLog File', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :changelogfile, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'DatabaseChangeLog Table', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :changelogtable, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'Application', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= collection_select(:schema, :application_id, Application.all, :id, :name) %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :'Environment', class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= collection_select(:schema, :environment_id, Environment.all, :id, :name) %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit @schema.new_record? ? 'Create' : 'Update', :class => 'btn btn-primary btn-xs' %>
      <%= link_to 'Cancel', schemas_path, :class => 'c_textlink' %>
    </div>
  </div>
  </form>

</div> 
<% end %>

app/views/schemas/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-database fa-2x"></i><big><big>Edit Schema:<b> <%= @schema.name %></b></big></big>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Schemas', schemas_path %></li>
  <li><%= link_to 'Add Schema', new_schema_path %></li>
</ul>

<%= render 'form' %>

app/views/schemas/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-database fa-2x"></i><b> <big><big>Schemas</big></big></b>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'Schemas', schemas_path %></li>
  <li><%= link_to 'Add Schema', new_schema_path %></li>
</ul>

<div class="table">

<table class="table table-striped table-bordered table-hover table-condensed ">
  <thead>
    <tr>
      <th class="col-md-3">Schema</th>
      <th class="col-md-3">Database Type</th>
      <th class="col-md-3">Hostname</th>
      <th class="col-md-3">Port</th>
      <th class="col-md-3">Status</th>
      <th class="col-md-3">Application</th>
      <th class="col-md-3">Environment</th>
      <th class="col-md-4"colspan="3" style="text-align:center;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @schemas.each do |schema| %>
      <tr>
        <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{schema.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{schema.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= link_to schema.name, schema, :class => 'c_textlink' %>
          </span>
        </td>
        <td><%= schema.database_type %></td>
        <td><%= schema.host %></td>
        <td><%= schema.port %></td>
        <td><big><%= raw get_Schema_Deployments_Status(schema) %></big></td>
        <td nowrap="true"><%= get_Application_Name(schema.application_id) %></td>
        <td nowrap="true"><%= get_Environment_Name(schema.environment_id) %></td>
        <td style="text-align:center;"><%= link_to 'Show', schema, class: 'btn btn-primary btn-xs c_btnlink' %></td>
        <td style="text-align:center;"><%= link_to 'Edit', edit_schema_path(schema), class: 'btn btn-primary btn-xs c_btnlink' %></td>
        <td style="text-align:center;"><%= link_to 'Destroy', schema, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-xs c_btnlink' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/schemas/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-database fa-2x"></i><b> <big><big>Add Schema</big></big></b>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Schemas', schemas_path %></li>
  <li class="active"><%= link_to 'Add Schema', new_schema_path %></li>
</ul>

<%= render 'form' %>

app/views/schemas/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <i class="fa fa-database fa-2x"></i><b> <big><big>Schema: <b><%= @schema.name %></big></big></b>
  </div>  
</div>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Schemas', schemas_path %></li>
  <li><%= link_to 'Add Schema', new_schema_path %></li>
</ul>

<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <colgroup>
      <col class="col-xs-3">
      <col class="col-xs-7">
    </colgroup>
    <tbody>
      <tr>
        <td><strong>Schema Name</strong></td>
  			<td><%= @schema.name %></td>
      </tr>
      <tr>
        <td><strong>Database Type</strong></td>
        <td><%= @schema.database_type %></td>
      </tr>
      <tr>
        <td><strong>Hostname</strong></td>
        <td><%= @schema.host %></td>
      </tr>
      <tr>
        <td><strong>Status</strong></td>
        <td><big><%= raw get_Schema_Deployments_Status(@schema) %></big></td>
      </tr>
      <tr
        <td><strong>Port</strong></td>
        <td><%= @schema.port %></td>
      </tr>
      <tr>
        <td><strong>Username</strong></td>
        <td><%= @schema.username %></td>
      </tr>
      <tr>
        <td><strong>Password</strong></td>
        <td><%= @schema.password %></td>
      </tr>
      <tr>
        <td><strong>ChangeLog File</strong></td>
        <td><%= @schema.changelogfile %></td>
      </tr>
      <tr>
        <td><strong>DatabaseChangeLog Name</strong></td>
  			<td><%= @schema.changelogtable %></td>
      </tr>
      <tr>
        <td><strong>Application</strong></td>
        <td><%= get_Application_Name(@schema.application_id) %></td>
      </tr>
      <tr>
        <td><strong>Environment</strong></td>
        <td><%= get_Environment_Name(@schema.environment_id) %></td>
      </tr>
    </tbody>
  </table>
 </div>

<%= link_to 'Edit', edit_schema_path(@schema), class: 'btn btn-success btn-xs' %> 
<%= link_to 'Status', database_change_logs_path(:id => @schema.id, :schemaName => @schema.name, :databaseChangeLogTable => @schema.changelogtable), class: 'btn btn-success btn-xs' %>
<%= link_to 'Back', :back, :class => 'c_textlink' %>